# Generated by Django 5.0.1 on 2026-01-23 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("authenticated", "Authenticated Users Only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Repository access controls",
                "db_table": "repository_access",
            },
        ),
        migrations.CreateModel(
            name="RepositoryMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata_type",
                    models.CharField(
                        choices=[
                            ("repomd", "Repository Metadata"),
                            ("primary", "Primary"),
                            ("filelists", "File Lists"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("checksum", models.CharField(max_length=128)),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Repository metadata",
                "db_table": "repository_metadata",
            },
        ),
        migrations.CreateModel(
            name="RepositoryPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=100)),
                ("release", models.CharField(max_length=50)),
                ("arch", models.CharField(max_length=20)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField()),
                ("checksum", models.CharField(max_length=128)),
                ("checksum_type", models.CharField(default="sha256", max_length=20)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "repository_packages",
                "ordering": ["name", "-version"],
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("rhel_version", models.CharField(max_length=20)),
                ("architecture", models.CharField(default="x86_64", max_length=20)),
                ("repo_path", models.CharField(max_length=500)),
                ("repo_url", models.URLField(blank=True, max_length=500)),
                ("baseurl", models.URLField(blank=True, max_length=500)),
                ("gpgcheck", models.BooleanField(default=True)),
                ("gpgkey_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "Creating"),
                            ("active", "Active"),
                            ("updating", "Updating"),
                            ("error", "Error"),
                            ("archived", "Archived"),
                        ],
                        default="creating",
                        max_length=20,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                ("package_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "repositories",
                "ordering": ["-created_at"],
            },
        ),
    ]
