# Generated by Django 5.0.1 on 2026-01-23 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("repositories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="repositoryaccess",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_repositories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="repositoryaccess",
            name="repository",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_control",
                to="repositories.repository",
            ),
        ),
        migrations.AddField(
            model_name="repositorymetadata",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata",
                to="repositories.repository",
            ),
        ),
        migrations.AddField(
            model_name="repositorypackage",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="repositories.repository",
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["project", "status"], name="repositorie_project_3be143_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["status"], name="repositorie_status_826bc4_idx"),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["rhel_version"], name="repositorie_rhel_ve_085246_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together={("project", "name", "rhel_version", "architecture")},
        ),
        migrations.AlterUniqueTogether(
            name="repositorymetadata",
            unique_together={("repository", "metadata_type")},
        ),
        migrations.AddIndex(
            model_name="repositorypackage",
            index=models.Index(
                fields=["repository", "name"], name="repository__reposit_0e7bf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repositorypackage",
            index=models.Index(fields=["name"], name="repository__name_9673be_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="repositorypackage",
            unique_together={("repository", "name", "version", "release", "arch")},
        ),
    ]
