# Generated by Django 5.0.1 on 2026-01-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("git_url", models.URLField(max_length=500)),
                ("git_branch", models.CharField(default="main", max_length=100)),
                ("git_tag", models.CharField(blank=True, max_length=100)),
                ("git_commit", models.CharField(blank=True, max_length=40)),
                (
                    "git_ssh_key",
                    models.TextField(
                        blank=True, help_text="SSH private key for repository access"
                    ),
                ),
                (
                    "git_api_token",
                    models.CharField(
                        blank=True,
                        help_text="API token for repository access",
                        max_length=255,
                    ),
                ),
                (
                    "requirements_file",
                    models.CharField(
                        default="requirements.txt",
                        help_text="Path to requirements file in repo",
                        max_length=255,
                    ),
                ),
                ("build_version", models.CharField(max_length=50)),
                (
                    "rhel_versions",
                    models.JSONField(
                        default=list,
                        help_text='List of RHEL versions to build for, e.g., ["8", "9"]',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("cloning", "Cloning"),
                            ("analyzing", "Analyzing Dependencies"),
                            ("ready", "Ready"),
                            ("building", "Building"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                (
                    "spec_repo_url",
                    models.URLField(
                        blank=True,
                        help_text="Git repository for storing spec file changes",
                        max_length=500,
                    ),
                ),
                ("spec_repo_ssh_key", models.TextField(blank=True)),
                ("spec_repo_api_token", models.CharField(blank=True, max_length=255)),
                (
                    "parallel_builds",
                    models.IntegerField(
                        default=1, help_text="Number of packages to build in parallel"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_build_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_trigger_build", "Can trigger project builds"),
                    ("can_edit_specs", "Can edit spec files"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("commit_hash", models.CharField(max_length=40)),
                ("is_tag", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "project_branches",
                "ordering": ["-is_tag", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectBuildConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("git_ref", models.CharField(max_length=255)),
                ("rhel_versions", models.JSONField(default=list)),
                (
                    "build_options",
                    models.JSONField(
                        default=dict, help_text="Additional build options as JSON"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "project_build_configs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer"),
                            ("builder", "Builder"),
                            ("maintainer", "Maintainer"),
                            ("admin", "Admin"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "project_collaborators",
            },
        ),
    ]
