# Generated by Django 5.0.1 on 2026-01-23 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectbranch",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectbuildconfig",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectbuildconfig",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="build_configs",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectcollaborator",
            name="added_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_collaborators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectcollaborator",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborators",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectcollaborator",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "status"], name="projects_owner_i_597fe2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="projects_status_6303d7_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["created_at"], name="projects_created_40bcd1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectbranch",
            unique_together={("project", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="projectbuildconfig",
            unique_together={("project", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="projectcollaborator",
            unique_together={("project", "user")},
        ),
    ]
