# Generated by Django 5.0.1 on 2026-01-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="requirements_file",
        ),
        migrations.AddField(
            model_name="project",
            name="requirements_files",
            field=models.JSONField(
                default=list,
                help_text='List of requirements file paths in repo, e.g., ["requirements.txt", "requirements/base.txt"]',
            ),
        ),
    ]
