# Generated by Django 5.0.1 on 2026-01-23 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_remove_project_requirements_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_logs",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["project", "timestamp"],
                        name="project_log_project_083810_idx",
                    ),
                    models.Index(
                        fields=["project", "level"],
                        name="project_log_project_fc3943_idx",
                    ),
                ],
            },
        ),
    ]
