# Generated by Django 5.0.1 on 2026-01-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_projectlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="build_repositories",
            field=models.TextField(
                blank=True,
                help_text="Additional YUM/DNF repositories to use during build (one per line)",
            ),
        ),
    ]
