# Generated by Django 5.0.1 on 2026-01-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_project_build_repositories"),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='python_version',
            field=models.CharField(
                default='3.11',
                help_text='Python version to use for spec generation (e.g., "3.11", "3.12")',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='mock_config',
            field=models.CharField(
                default='rhel-10-x86_64',
                help_text='Mock configuration to use for builds (e.g., "rhel-9-x86_64", "rhel-10-x86_64")',
                max_length=100
            ),
        ),
    ]
