# Generated by Django 5.0.1 on 2026-01-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_add_python_version_and_mock_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="mock_config",
        ),
        migrations.AlterField(
            model_name="project",
            name="python_version",
            field=models.CharField(
                default="default",
                help_text='Python version to use for spec generation (e.g., "3.11", "3.12", or "default")',
                max_length=10,
            ),
        ),
    ]
