# Generated by Django 5.0.1 on 2026-02-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_remove_mock_config_update_python_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="rhel_version",
            field=models.CharField(
                default="9",
                help_text='RHEL version to build for (e.g., "8", "9")',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="rhel_versions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="DEPRECATED: Use rhel_version instead",
                null=True,
            ),
        ),
    ]
