# Generated by Django 5.0.1 on 2026-01-26 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_concurrent_builds",
                    models.IntegerField(
                        default=4,
                        help_text="Maximum number of simultaneous builds (1-20)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "cleanup_builds_after_days",
                    models.IntegerField(
                        default=30,
                        help_text="Remove build artifacts older than N days",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "cleanup_repos_after_days",
                    models.IntegerField(
                        default=7,
                        help_text="Remove old git repository clones after N days",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "auto_sync_projects",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically sync projects from git repositories",
                    ),
                ),
                (
                    "sync_interval_hours",
                    models.IntegerField(
                        default=6,
                        help_text="Hours between automatic project syncs",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "repository_sync_interval_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="Minutes between repository metadata syncs",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
