# Generated by Django 5.0.1 on 2026-06-10 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="ai_fixer_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="API key for OpenAI-compatible backends",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="ai_fixer_backend",
            field=models.CharField(
                choices=[
                    ("builtin", "Built-in (llama.cpp, no external services)"),
                    ("ollama", "Ollama"),
                    ("openai", "OpenAI-compatible API"),
                ],
                default="builtin",
                help_text="LLM backend to use",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="ai_fixer_base_url",
            field=models.CharField(
                blank=True,
                default="http://localhost:11434",
                help_text="Base URL for ollama/openai backends",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="ai_fixer_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Use an LLM as fallback when rule-based build fixers fail",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="ai_fixer_model",
            field=models.CharField(
                default="qwen2.5-coder-3b",
                help_text="Model key (builtin) or model name (ollama/openai)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="ai_fixer_timeout",
            field=models.IntegerField(
                default=300,
                help_text="LLM request timeout in seconds",
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(1800),
                ],
            ),
        ),
    ]
