# Generated by Django 5.0.1 on 2026-06-11 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_systemsettings_ai_fixer_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="ai_fixer_max_attempts",
            field=models.IntegerField(
                default=3,
                help_text="Maximum number of AI fix attempts per package before giving up",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
