# Generated by Django 5.0.1 on 2026-06-11 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_ai_fixer_max_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="ai_fixer_max_concurrent",
            field=models.IntegerField(
                default=1,
                help_text="Maximum number of packages the AI fixer may work on simultaneously",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
