# Generated by Django 5.0.1 on 2026-01-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "python_name",
                    models.CharField(
                        help_text="Original Python package name from PyPI",
                        max_length=255,
                    ),
                ),
                ("version", models.CharField(max_length=100)),
                ("release", models.CharField(default="1", max_length=50)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("dependency", "Dependency"),
                            ("main", "Main Project"),
                            ("extra", "Extra Package"),
                        ],
                        default="dependency",
                        max_length=20,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("homepage", models.URLField(blank=True, max_length=500)),
                ("license", models.CharField(blank=True, max_length=100)),
                (
                    "requirement_spec",
                    models.CharField(
                        blank=True,
                        help_text='Original requirement specification, e.g., "package>=1.0,<2.0"',
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("analyzing", "Analyzing Dependencies"),
                            ("ready", "Ready to Build"),
                            ("building", "Building"),
                            ("built", "Built"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                (
                    "build_order",
                    models.IntegerField(
                        default=0,
                        help_text="Build order based on dependency tree, 0 = no dependencies",
                    ),
                ),
                ("spec_file_content", models.TextField(blank=True)),
                ("spec_file_path", models.CharField(blank=True, max_length=500)),
                ("spec_file_modified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_built_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "packages",
                "ordering": ["build_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PackageBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rhel_version", models.CharField(max_length=20)),
                ("architecture", models.CharField(default="x86_64", max_length=20)),
                ("mock_config", models.CharField(max_length=255)),
                ("build_log", models.TextField(blank=True)),
                ("build_log_path", models.CharField(blank=True, max_length=500)),
                ("srpm_path", models.CharField(blank=True, max_length=500)),
                (
                    "rpm_paths",
                    models.JSONField(
                        default=list, help_text="List of paths to built RPM files"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("building", "Building"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "build_duration",
                    models.IntegerField(
                        blank=True, help_text="Build duration in seconds", null=True
                    ),
                ),
                ("builder_host", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "package_builds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("build", "Build Dependency"),
                            ("runtime", "Runtime Dependency"),
                            ("both", "Build and Runtime"),
                        ],
                        default="build",
                        max_length=20,
                    ),
                ),
                (
                    "version_constraint",
                    models.CharField(
                        blank=True,
                        help_text='Version constraint, e.g., ">= 1.0"',
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Package dependencies",
                "db_table": "package_dependencies",
            },
        ),
        migrations.CreateModel(
            name="SpecFileRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("commit_message", models.TextField()),
                ("git_commit_hash", models.CharField(blank=True, max_length=40)),
                ("git_commit_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "spec_file_revisions",
                "ordering": ["-created_at"],
            },
        ),
    ]
