# Generated by Django 5.0.1 on 2026-01-23 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("packages", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="packagebuild",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="builds",
                to="packages.package",
            ),
        ),
        migrations.AddField(
            model_name="packagedependency",
            name="depends_on",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependents",
                to="packages.package",
            ),
        ),
        migrations.AddField(
            model_name="packagedependency",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependencies",
                to="packages.package",
            ),
        ),
    ]
