# Generated by Django 5.0.1 on 2026-01-23 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("packages", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="specfilerevision",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spec_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="specfilerevision",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spec_revisions",
                to="packages.package",
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["project", "status"], name="packages_project_450c5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["status"], name="packages_status_3149ce_idx"),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["build_order"], name="packages_build_o_8db172_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["package_type"], name="packages_package_54127e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="package",
            unique_together={("project", "name", "version")},
        ),
        migrations.AddIndex(
            model_name="packagebuild",
            index=models.Index(
                fields=["package", "status"], name="package_bui_package_c64ff2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packagebuild",
            index=models.Index(fields=["status"], name="package_bui_status_02e7cb_idx"),
        ),
        migrations.AddIndex(
            model_name="packagebuild",
            index=models.Index(
                fields=["rhel_version"], name="package_bui_rhel_ve_88d1c2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="packagebuild",
            unique_together={("package", "rhel_version", "architecture")},
        ),
        migrations.AlterUniqueTogether(
            name="packagedependency",
            unique_together={("package", "depends_on")},
        ),
    ]
