# Generated by Django 5.0.1 on 2026-01-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "db_table": "package_logs",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["package", "timestamp"],
                        name="package_log_package_85b277_idx",
                    ),
                    models.Index(
                        fields=["package", "level"],
                        name="package_log_package_232fa7_idx",
                    ),
                ],
            },
        ),
    ]
