# Generated by Django 5.0.1 on 2026-01-24 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0004_packagelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the extra feature (e.g., security, socks)",
                        max_length=100,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this extra should be included in the spec file",
                    ),
                ),
                (
                    "dependencies",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of dependencies for this extra",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "db_table": "package_extras",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["package", "enabled"],
                        name="package_ext_package_52c1f7_idx",
                    )
                ],
                "unique_together": {("package", "name")},
            },
        ),
    ]
