# Generated by Django 5.0.1 on 2026-02-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0005_packageextra"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="is_direct_dependency",
            field=models.BooleanField(
                default=False,
                help_text="True if package is directly listed in requirements files, False if indirect dependency",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="requirements_file",
            field=models.CharField(
                blank=True,
                help_text="Requirements file this package was defined in (for direct dependencies)",
                max_length=500,
            ),
        ),
    ]
