# Generated by Django 5.0.1 on 2026-02-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0006_package_is_direct_dependency_and_more"),
        ("projects", "0008_project_rhel_version_alter_project_rhel_versions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveIndex(
            model_name="package",
            name="packages_build_o_8db172_idx",
        ),
        migrations.AddField(
            model_name="package",
            name="build_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="build_error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="package",
            name="build_log",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="package",
            name="build_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="build_status",
            field=models.CharField(
                choices=[
                    ("not_built", "Not Built"),
                    ("pending", "Pending"),
                    ("building", "Building"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="not_built",
                help_text="Current build status for this package",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="rpm_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="package",
            name="srpm_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="package",
            name="build_order",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="DEPRECATED: Build order no longer used, builds happen on-demand",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["project", "build_status"], name="packages_project_e71d00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["build_status"], name="packages_build_s_e294f0_idx"
            ),
        ),
    ]
