# Generated by Django 5.0.1 on 2026-02-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0007_alter_package_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="rpm_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="srpm_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
