# Generated by Django 5.0.1 on 2026-02-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0008_alter_package_rpm_path_alter_package_srpm_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="build_status",
            field=models.CharField(
                choices=[
                    ("not_built", "Not Built"),
                    ("waiting_for_deps", "Waiting for Dependencies"),
                    ("pending", "Pending"),
                    ("building", "Building"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="not_built",
                help_text="Current build status for this package",
                max_length=20,
            ),
        ),
    ]
