# Generated by Django 5.0.1 on 2026-02-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0009_alter_package_build_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="analyzed_errors",
            field=models.JSONField(
                blank=True, default=list, help_text="Parsed build error analysis"
            ),
        ),
    ]
