# Generated by Django 5.0.1 on 2026-04-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0013_package_dep_build_pending_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="build_root_log",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="python_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Original Python package name from PyPI",
                max_length=255,
            ),
        ),
    ]
