# Generated by Django 5.0.1 on 2026-06-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0014_add_build_root_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="specfilerevision",
            name="fix_context",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Error fingerprint + actions stored for AI few-shot retrieval",
                null=True,
            ),
        ),
    ]
