# Generated by Django 5.0.1 on 2026-07-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0015_spec_revision_fix_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="sources_fetched_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When sources were last successfully fetched",
                null=True,
            ),
        ),
    ]
