# Generated by Django 5.0.1 on 2026-07-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0016_add_sources_fetched_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="build_dependency_repo_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Local dependency repo URL used for this build (project-scoped)",
                max_length=500,
            ),
        ),
    ]
