# Generated by Django 5.0.1 on 2026-01-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("build_version", models.CharField(max_length=50)),
                ("git_ref", models.CharField(max_length=255)),
                ("git_commit", models.CharField(max_length=40)),
                ("rhel_versions", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("preparing", "Preparing"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                ("total_packages", models.IntegerField(default=0)),
                ("completed_packages", models.IntegerField(default=0)),
                ("failed_packages", models.IntegerField(default=0)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "build_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuildQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rhel_version", models.CharField(max_length=20)),
                ("architecture", models.CharField(default="x86_64", max_length=20)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority builds first"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("building", "Building"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("dependencies_met", models.BooleanField(default=False)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "build_queue",
                "ordering": ["-priority", "package__build_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuildWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=255, unique=True)),
                ("celery_worker_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("busy", "Busy"),
                            ("offline", "Offline"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("max_concurrent_builds", models.IntegerField(default=1)),
                ("current_builds", models.IntegerField(default=0)),
                ("total_builds", models.IntegerField(default=0)),
                ("successful_builds", models.IntegerField(default=0)),
                ("failed_builds", models.IntegerField(default=0)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "build_workers",
                "ordering": ["hostname"],
            },
        ),
    ]
