# Generated by Django 5.0.1 on 2026-01-23 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("builds", "0002_initial"),
        ("packages", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="buildjob",
            name="triggered_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_builds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="buildqueue",
            name="blocked_by",
            field=models.ManyToManyField(
                blank=True, related_name="blocking", to="builds.buildqueue"
            ),
        ),
        migrations.AddField(
            model_name="buildqueue",
            name="build_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_items",
                to="builds.buildjob",
            ),
        ),
        migrations.AddField(
            model_name="buildqueue",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_items",
                to="packages.package",
            ),
        ),
        migrations.AddIndex(
            model_name="buildjob",
            index=models.Index(
                fields=["project", "status"], name="build_jobs_project_85c8c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="buildjob",
            index=models.Index(fields=["status"], name="build_jobs_status_04daaf_idx"),
        ),
        migrations.AddIndex(
            model_name="buildjob",
            index=models.Index(
                fields=["created_at"], name="build_jobs_created_1bbf88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="buildqueue",
            index=models.Index(
                fields=["build_job", "status"], name="build_queue_build_j_1a2f38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="buildqueue",
            index=models.Index(
                fields=["status", "dependencies_met"],
                name="build_queue_status_846f78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="buildqueue",
            index=models.Index(
                fields=["package"], name="build_queue_package_ccae3d_idx"
            ),
        ),
    ]
