# Generated by Django 5.0.1 on 2026-01-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builds", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildqueue",
            name="build_log",
            field=models.TextField(blank=True, help_text="Build output log"),
        ),
        migrations.AddField(
            model_name="buildqueue",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error message if build failed"
            ),
        ),
        migrations.AddField(
            model_name="buildqueue",
            name="rpm_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="buildqueue",
            name="srpm_path",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
