# Generated by Django 5.0.1 on 2026-01-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builds", "0004_buildqueue_build_log_buildqueue_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildqueue",
            name="analyzed_errors",
            field=models.JSONField(
                blank=True, default=list, help_text="Analyzed errors from build log"
            ),
        ),
    ]
